/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package libmealone;

/**
 *
 * @author Zeus
 */
public class Book extends javax.swing.JPanel {
    private Integer id;
    private String title;
    private String author;
    
    /**
     * Creates new form Book
     */
    public Book() {
        initComponents();
    }
    
    public Book(int id, String title, String author) {
        initComponents();
        
        this.id = id;
        this.title = title;
        this.author = author;
        
        book_title.setText(title);
        book_author.setText(author);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        book_title = new javax.swing.JLabel();
        book_author = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 102, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_title.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        book_title.setText("(TITLE)");
        add(book_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 30));

        book_author.setText("(Book Author)");
        add(book_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 80, 20));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 150));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_title;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
