/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libmealone;

import database.MyDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Zeus
 */
public class BorrowedBooks extends javax.swing.JFrame {
    private Integer offset;
    private Boolean isRequested;
    /**
     * Creates new form BorrowedBooks
     */
    public BorrowedBooks() {
        initComponents();
        offset = 0;
        offset_label.setText(offset.toString());
        updateTable();
    }
    
    public BorrowedBooks(Boolean isRequested) {
        initComponents();
        offset = 0;
        
        this.isRequested = isRequested;
        
        if(isRequested) {
            main_label.setText("Books Requested");
        }
        else {
            main_label.setText("Books Borrowed");
        }
        
        offset_label.setText(offset.toString());
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        main_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_area = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        offset_label = new javax.swing.JLabel();
        minus_offset = new javax.swing.JButton();
        plus_offset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        main_label.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        main_label.setText("<BOOKS>");
        jPanel1.add(main_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        table_area.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Borrow ID", "Book ID", "Book Title", "Book Author", "User ID", "Borrower", "Date borrowed"
            }
        ));
        table_area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_areaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 550, 250));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        offset_label.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        offset_label.setText("<number>");
        offset_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        offset_label.setVerifyInputWhenFocusTarget(false);
        jPanel2.add(offset_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 30, 40));

        minus_offset.setText("<");
        minus_offset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus_offsetMouseClicked(evt);
            }
        });
        minus_offset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minus_offsetActionPerformed(evt);
            }
        });
        jPanel2.add(minus_offset, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        plus_offset.setText(">");
        plus_offset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus_offsetMouseClicked(evt);
            }
        });
        plus_offset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plus_offsetActionPerformed(evt);
            }
        });
        plus_offset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                plus_offsetKeyPressed(evt);
            }
        });
        jPanel2.add(plus_offset, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 150, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void table_areaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_areaMouseClicked
        int row = table_area.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)table_area.getModel();
        
        Integer bb_id = (Integer)model.getValueAt(row, 0);
        Integer book_id = (Integer)model.getValueAt(row, 1);
        String book_name = (String)model.getValueAt(row, 2);
        
        // open borrow book with passed ids
        new ReturnBook(isRequested, bb_id, book_id, book_name, ()-> {
            updateTable();
            return null;
        }).setVisible(true);
    }//GEN-LAST:event_table_areaMouseClicked

    private void minus_offsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus_offsetMouseClicked
        if(offset > 0) {
            offset--;
            offset_label.setText(offset.toString());
            updateTable();
        }
    }//GEN-LAST:event_minus_offsetMouseClicked

    private void minus_offsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minus_offsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minus_offsetActionPerformed

    private void plus_offsetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus_offsetMouseClicked
        offset++;
        offset_label.setText(offset.toString());
        updateTable();
    }//GEN-LAST:event_plus_offsetMouseClicked

    private void plus_offsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plus_offsetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plus_offsetActionPerformed

    private void plus_offsetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plus_offsetKeyPressed

    }//GEN-LAST:event_plus_offsetKeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowedBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowedBooks().setVisible(true);
            }
        });
    }
    
    private void updateTable() {
        DefaultTableModel model = (DefaultTableModel)table_area.getModel();
        
        while(table_area.getRowCount() > 0) {
            model.removeRow(0);
        }
        
        table_area.removeAll();
        table_area.revalidate();
        table_area.repaint(); 
        
        try {
           Connection conn = MyDB.getConn();
           
            String sql1 ;
                    
            if(!isRequested) {
                sql1 = ("""
                           SELECT *, bb.id AS bb_id 
                           FROM borrowed_books bb
                           JOIN users u ON bb.user_id = u.id
                           JOIN books b ON bb.book_id = b.id
                           WHERE bb.is_returned = 0 AND bb.is_approved = 1
                           ORDER BY date_borrowed ASC
                           LIMIT 10
                           OFFSET ?""");
            }
            else {
                sql1 = ("""
                           SELECT *, bb.id AS bb_id 
                           FROM borrowed_books bb
                           JOIN users u ON bb.user_id = u.id
                           JOIN books b ON bb.book_id = b.id
                           WHERE bb.is_returned = 0 AND bb.is_approved = 0
                           ORDER BY date_borrowed ASC
                           LIMIT 10
                           OFFSET ?""");
            }
            
            PreparedStatement p1 = conn.prepareStatement(sql1);
            p1.setInt(1, offset * 10);

            ResultSet rs = p1.executeQuery();
            
            while(rs.next()) {
                model.addRow(new Object[]{rs.getInt("bb_id"),rs.getInt("book_id"), rs.getString("name"), rs.getString("author"), rs.getInt("user_id"), rs.getString("username"), rs.getDate("date_borrowed")});
            }
            
            conn.close();
       }
       catch(Exception error) {
           System.out.println(error);
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel main_label;
    private javax.swing.JButton minus_offset;
    private javax.swing.JLabel offset_label;
    private javax.swing.JButton plus_offset;
    private javax.swing.JTable table_area;
    // End of variables declaration//GEN-END:variables
}
