/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libmealone;

import java.sql.*;
import database.MyDB;
import database.SessionManager;
import javax.swing.JOptionPane;

/**
 *
 * @author Zeus
 */
public class BorrowMe extends javax.swing.JFrame {
    private Integer id;
    private String title;
    private String author;
    private String description;
    /**
     * Creates new form BorrowMe
     */
    public BorrowMe() {
        initComponents();
    }
    
    public BorrowMe(Integer id, String title, String author, String description) {
        initComponents();
        
        this.id = id;
        this.title = title;
        this.author = author;
        this.description = description;
        
        book_author.setText(author);
        book_name.setText(title);
        description_box.setText("<html><p>"+ description + "</p></html>");
        
        String role = SessionManager.get("role").toString();
        if (!role.equals("user")) {
            borrow_button.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        book_name = new javax.swing.JLabel();
        book_author = new javax.swing.JLabel();
        description_box = new javax.swing.JLabel();
        borrow_button = new javax.swing.JButton();
        close_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_name.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        book_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        book_name.setText("<Book Name>");
        jPanel1.add(book_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, -1));

        book_author.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        book_author.setText("<Book Author>");
        jPanel1.add(book_author, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, -1));

        description_box.setText("<Description>");
        description_box.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        description_box.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(description_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 250, 80));

        borrow_button.setBackground(java.awt.Color.green);
        borrow_button.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        borrow_button.setText("Borrow");
        borrow_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrow_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(borrow_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 150, 80, -1));

        close_button.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        close_button.setText("Close");
        close_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(close_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 180, 80, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_buttonMouseClicked
        this.dispose();
    }//GEN-LAST:event_close_buttonMouseClicked

    private void borrow_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrow_buttonMouseClicked
        try {
           Connection conn = MyDB.getConn();
           Integer user_id = Integer.valueOf(SessionManager.get("id").toString());
            // Check if username already exists
            String sql = "SELECT * FROM borrowed_books WHERE user_id = ? AND book_id = ? AND is_approved = 0";
            
            PreparedStatement p = conn.prepareStatement(sql);
            
            p.setInt(1, user_id);
            p.setInt(2, id);
            
            ResultSet rs = p.executeQuery();
            
            if(rs.next()) {
                JOptionPane.showMessageDialog(this, "You already submitted a request for this book");
            }
            else {
                String sql1 = "INSERT INTO borrowed_books(user_id, book_id) VALUES(?, ?)";
                PreparedStatement p1 = conn.prepareStatement(sql1);


                p1.setInt(1, user_id);
                p1.setInt(2, this.id);

                p1.execute();
                JOptionPane.showMessageDialog(this, "Successfully borred book!");
            }
            
            
            conn.close();
       }
        catch(Exception error) {
            System.err.println(error);
            JOptionPane.showMessageDialog(this, "Error: Invalid borrow attempt.");
        }
        
        this.dispose();
    }//GEN-LAST:event_borrow_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowMe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel book_author;
    private javax.swing.JLabel book_name;
    private javax.swing.JButton borrow_button;
    private javax.swing.JButton close_button;
    private javax.swing.JLabel description_box;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
