/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package libmealone;

import database.MyDB;
import database.SessionManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.concurrent.Callable;

/**
 *
 * @author Zeus
 */
public class ReturnBook extends javax.swing.JFrame {
    private Integer bb_id;
    private Integer book_id;
    private Callable<Void> update;
    private Boolean isRequested;
    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
    }
    
    public ReturnBook(Boolean isRequested, Integer bb_id, Integer book_id, String book_name, Callable<Void> call) {
        initComponents();
        
        this.bb_id = bb_id;
        this.book_id = book_id;
        
        this.isRequested = isRequested;
        
        String action = (isRequested) ? "Approve " : "Return ";
        action_button.setText(isRequested ? "Approve" : "Return");
        
        this.return_label.setText("<html><p>" + action + book_name + "?<p></html>");
        
        this.update = call;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        return_label = new javax.swing.JLabel();
        action_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        return_label.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        return_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        return_label.setText("Return <>?");
        return_label.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        return_label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(return_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 10, 230, 80));

        action_button.setBackground(java.awt.Color.green);
        action_button.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        action_button.setText("Return");
        action_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                action_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(action_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void action_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_action_buttonMouseClicked
        try {
           Connection conn = MyDB.getConn();
           PreparedStatement p1, p2;
           
           if(!isRequested) {
               String sql1 = "UPDATE borrowed_books SET is_returned = 1 WHERE id = ?";
            
                p1 = conn.prepareStatement(sql1);

                p1.setInt(1, this.bb_id);

                String sql2 = "UPDATE books SET is_borrowed = 0 WHERE id = ?";

                p2 = conn.prepareStatement(sql2);

                p2.setInt(1, this.book_id);
           }
           else {
                String sql1 = "UPDATE borrowed_books SET is_approved = 1 WHERE id = ?";
            
                p1 = conn.prepareStatement(sql1);

                p1.setInt(1, this.bb_id);

                String sql2 = "UPDATE books SET is_borrowed = 1 WHERE id = ?";

                p2 = conn.prepareStatement(sql2);

                p2.setInt(1, this.book_id);

                
           }
           
            p1.execute();
            p2.execute();
            
            update.call();
            
            conn.close();
       }
       catch(Exception error) {
           System.out.println(error);
       }
        
        this.dispose();
    }//GEN-LAST:event_action_buttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton action_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel return_label;
    // End of variables declaration//GEN-END:variables

}
